# -*- coding: utf-8 -*-
SPORTS = [
    {
        "hero": True,
        "sub": "Tennis",
        "h3": "Muchova stuns Gauff to set up all-Czech Wimbledon final",
        "summary": "Karolina Muchova saved a match point to beat Coco Gauff and will meet countrywoman Linda Noskova in the first ever all-Czech Grand Slam singles final.",
        "body": ["Tenth seed Karolina Muchova outlasted seventh seed Coco Gauff 6-2, 1-6, 7-6 (12-10) in a rollercoaster Wimbledon semifinal on Thursday. Muchova fought off a match point at 10-9 in the deciding tiebreak before finally closing out the win on Centre Court.", "Ninth seed Linda Noskova beat Marta Kostyuk 6-4, 7-5 in the second semifinal, meaning Saturday's championship will pit two Czech players against each other for the first time in Grand Slam singles final history. Both women are chasing a maiden major title."],
        "sources": [("CBS Sports", "https://www.cbssports.com/tennis/news/wimbledon-2026-schedule-bracket-live-updates-results-scores-matches-where-to-watch/live/"), ("ESPN", "https://www.espn.com/tennis/story/_/id/49313045/wimbledon-2026-today-blog-09-07-2026-live-updates-news-schedule-results-coco-gauff-karolina-muchova-marta-kostyuk-linda-noskova")],
    },
    {
        "sub": "Tennis",
        "h3": "Sinner and Djokovic renew rivalry in Wimbledon semifinal",
        "summary": "World number one and defending champion Jannik Sinner faces seven-time winner Novak Djokovic on Centre Court in a repeat of last year's last-four clash.",
        "body": ["The men's semifinals take place on Friday with Jannik Sinner meeting Novak Djokovic for the second year running at the All England Club. Sinner, the top seed and reigning champion, goes up against the 24-time major winner in a blockbuster Centre Court showdown.", "The two matches determine who reaches Sunday's final. Djokovic reached the last four after an epic five-set quarterfinal win over Felix Auger-Aliassime that ran 5 hours 15 minutes, the longest quarterfinal in tournament history."],
        "sources": [("ATP Tour", "https://www.atptour.com/en/news/wimbledon-2026-sfs-all-you-need-to-know"), ("Olympics.com", "https://www.olympics.com/en/news/wimbledon-2026-jannik-sinner-novak-djokovic-semi-final-schedule-watch-live")],
    },
    {
        "sub": "Tennis",
        "h3": "British wild card Fery lands fairytale semifinal against Zverev",
        "summary": "Home hope Arthur Fery continued a dream Wimbledon run and will face Roland Garros champion Alexander Zverev for a place in the final.",
        "body": ["Arthur Fery became the story of the tournament for the home crowd, reaching the semifinals as a British wild card. He beat ninth seed Flavio Cobolli 6-4, 7-6 (4), 6-0 on Centre Court to book his spot in the final four.", "Fery now meets Alexander Zverev, who reached the semifinals by defeating Taylor Fritz in the quarterfinals. Zverev, fresh off winning last month's French Open, starts as a heavy favourite in the first semifinal."],
        "sources": [("ESPN", "https://www.espn.com/tennis/story/_/id/49313045/wimbledon-2026-today-blog-09-07-2026-live-updates-news-schedule-results-coco-gauff-karolina-muchova-marta-kostyuk-linda-noskova"), ("Tennis Temple", "https://en.tennistemple.com/actu/wimbledon-semifinals-zverev-opens-against-fairy/CZry")],
    },
    {
        "sub": "Football",
        "h3": "Tottenham lead frantic Premier League summer spending",
        "summary": "Spurs have added Sandro Tonali, Andrew Robertson and several others under Roberto De Zerbi as clubs push hard before the September deadline.",
        "body": ["Tottenham have been the busiest club in the Premier League window, signing Sandro Tonali, Mateus Fernandes, Jan Paul van Hecke, Andrew Robertson, Marcos Senesi and Martin Dubravka as Roberto De Zerbi rebuilds after a poor 2025-26 season.", "Chelsea have also been active with the arrivals of Marco Palestra, Geovany Quenda, Emmanuel Emegha and others, while Manchester City announced a club-record fee for Nottingham Forest midfielder Elliot Anderson. The window closes at 11pm UK time on September 1."],
        "sources": [("Sky Sports", "https://www.skysports.com/football/news/11095/13546618/transfer-news-summer-transfer-window-2026-premier-league-deals-ins-and-outs"), ("ESPN", "https://www.espn.com/soccer/story/_/id/48955344/premier-league-2026-summer-transfers-all-confirmed-ins-outs-every-club")],
    },
    {
        "sub": "Football",
        "h3": "Eredivisie big three miss out on 30m euro striker Rodriguez",
        "summary": "Ajax, PSV and Feyenoord all chased Alvaro Rodriguez but the striker picked the Premier League and Bournemouth instead.",
        "body": ["Ajax, PSV and Feyenoord all pursued Elche striker Alvaro Rodriguez, but the 21-year-old Real Madrid academy product chose England over the Eredivisie, joining Bournemouth in a deal valued at around 30 million euros with a five-year contract.", "The Dutch clubs have still been active elsewhere. Ajax added Daley Blind from Girona and Caio Henrique from Monaco, while PSV signed Sven Mijnans from AZ. The Dutch transfer window runs from June 22 to September 2."],
        "sources": [("FootballTransfers", "https://www.footballtransfers.com/nl/transfernieuws/nl-eredivisie/2026/07/feyenoord-ajax-en-psv-zien-spits-afhaken-door-transfer-van-30-miljoen")],
    },
    {
        "sub": "Football",
        "h3": "Manchester City break record for Elliot Anderson",
        "summary": "City announced the arrival of Nottingham Forest midfielder Elliot Anderson for a club-record fee alongside winger Mathys Detourbet.",
        "body": ["Manchester City confirmed the signing of Nottingham Forest midfielder Elliot Anderson for a club-record fee, a statement move in a summer where several Premier League sides are spending heavily. City also added winger Mathys Detourbet from Troyes.", "The deal signals City's intent to refresh their midfield after a competitive 2025-26 season. Rivals including Chelsea and Tottenham have matched the aggression in the market as clubs jostle before the September deadline."],
        "sources": [("Sky Sports", "https://www.skysports.com/football/news/11095/13546618/transfer-news-summer-transfer-window-2026-premier-league-deals-ins-and-outs")],
    },
    {
        "sub": "Formula 1",
        "h3": "F1 pauses before Belgian GP as Antonelli momentum builds",
        "summary": "With no race over the weekend of July 10 to 12, attention turns to Spa on July 17 to 19 after Kimi Antonelli's recent Silverstone pole.",
        "body": ["Formula 1 is in a rare quiet stretch with no grand prix on the weekend of July 10 to 12. The most recent round was the British Grand Prix at Silverstone from July 3 to 5, and the next event is the Belgian Grand Prix at Spa-Francorchamps from July 17 to 19.", "Mercedes youngster Kimi Antonelli grabbed pole at Silverstone, his fifth of the season, ahead of Ferrari pair Charles Leclerc and Lewis Hamilton. The championship fight remains tight heading into the second half of the calendar."],
        "sources": [("Formula 1", "https://www.formula1.com/en/latest/article/antonelli-seizes-pole-position-in-british-grand-prix-qualifying-ahead-of-leclerc-and-hamilton.4khQMdOBw2bmuaEWThYEk7"), ("PlanetF1", "https://www.planetf1.com/news/f1-schedule-next-race-calendar")],
    },
    {
        "sub": "Sailing",
        "h3": "SailGP fleet awaits Portsmouth showdown later this month",
        "summary": "The Rolex SailGP season continues with the Emirates Great Britain event scheduled for late July after Spain's win in Canada.",
        "body": ["SailGP is between events in early July, with the next round being the Emirates Great Britain Sail Grand Prix in Portsmouth scheduled for the second half of the month. The season runs across thirteen events, ending with the Grand Final in Abu Dhabi in late November.", "Spain's Los Gallos team, skippered by Diego Botin, won the Canada Sail Grand Prix on June 20 and 21, keeping the reigning champions near the top of the standings as the F50 fleet prepares to race on home water for the British team."],
        "sources": [("SailGP", "https://sailgp.com/results/all-seasons/"), ("US SailGP Team", "https://www.ussailgpteam.com/schedule")],
    },
    {
        "sub": "Grappling",
        "h3": "ADCC world championship looms as grappling stars sharpen up",
        "summary": "The 2026 ADCC World Championship in Krakow in September is drawing closer as the sport's elite prepare for the biggest no-gi event.",
        "body": ["The 2026 ADCC World Championship, submission grappling's marquee event, is set for September 12 and 13 at the Tauron Arena in Krakow, Poland. The invitation-only tournament brings together the best no-gi grapplers across weight classes plus the open-weight superfight.", "The competitive calendar has been busy in the build-up, with trials events around the world locking in the final invites. Mayssa Bastos was among those who secured a place by winning a South American Trials bracket."],
        "sources": [("FloGrappling", "https://www.flograppling.com/articles/15999094-when-is-the-2026-no-gi-bjj-adcc-world-championship"), ("MMA Mania", "https://www.mmamania.com/bjj-news/430898/bjj-star-mayssa-bastos-wins-trials-adcc-2026-invite-2nd-adcc-south-american-trials-results-highlights")],
    },
    {
        "sub": "Grappling",
        "h3": "Pessanha and Dalpra headline IBJJF Worlds champions list",
        "summary": "The gi jiu-jitsu season peaked at the IBJJF World Championship in Long Beach, where Gabrieli Pessanha and Tainan Dalpra took gold.",
        "body": ["The 2026 IBJJF World Championship crowned black belt champions across every weight class in Long Beach, California. Gabrieli Pessanha won both the female super-heavyweight and absolute divisions, cementing her status as one of the sport's dominant figures.", "On the men's side Tainan Dalpra took the 82kg title and Diego Pato won at 64kg. The event is the pinnacle of the gi competition calendar and served as a key marker ahead of the no-gi ADCC event later in the year."],
        "sources": [("BJJ Heroes", "https://www.bjjheroes.com/bjj-news/ibjjf-world-championship-2026-results"), ("FloGrappling", "https://www.flograppling.com/articles/15951418-ibjjf-worlds-2026-results-heres-every-division-winner")],
    },
    {
        "sub": "Grappling",
        "h3": "UFC International Fight Week takes over Las Vegas",
        "summary": "The promotion's flagship summer stretch runs through Las Vegas with a Fight Night on July 11 kicking off a packed month.",
        "body": ["UFC International Fight Week is under way in Las Vegas, the promotion's biggest annual gathering of fans and fighters. A Fight Night event follows on July 11 at the T-Mobile Arena to open a busy stretch of cards.", "The month continues with Du Plessis facing Usman in Oklahoma City on July 18 and Ankalaev meeting Rountree Jr in Abu Dhabi on July 25, giving grappling and striking fans a full slate through the summer."],
        "sources": [("UFC", "https://www.ufc.com/events"), ("ESPN", "https://www.espn.com/mma/schedule/_/league/ufc")],
    },
]

CONSUMER_TECH = [
    {
        "hero": True,
        "sub": "EVs & Mobility",
        "h3": "Tesla robotaxi service goes live in Miami",
        "summary": "Tesla launched its driverless ride-hailing service in western Miami-Dade, its first robotaxi expansion outside Texas and California.",
        "body": ["Tesla switched on its Robotaxi service in western Miami-Dade on July 3, marking the first time the driverless network has operated beyond Texas and California. The service covers parts of western and central Miami, excluding downtown and Miami Beach, using Model Y vehicles with no driver or safety monitor inside.", "The company is framing 2026 as its most important investment year since the Model 3 ramp as it tries to turn Robotaxi from a geofenced pilot into a national network. Shares jumped roughly 6.7 percent after the launch, though analysts note the rollout is behind Elon Musk's earlier projections of more cities by mid-2026."],
        "sources": [("TechTimes", "https://www.techtimes.com/articles/319711/20260704/tesla-robotaxi-arrives-miami-floridas-rain-hardest-test-yet-camera-only-fsd.htm"), ("The Motley Fool", "https://www.fool.com/investing/2026/07/09/some-good-and-bad-news-for-tesla-investors/")],
    },
    {
        "sub": "Devices & Launches",
        "h3": "Meta rolls out Muse Image generator to WhatsApp and Instagram",
        "summary": "Meta launched its first in-house image model, Muse Image, powering new AI effects across Instagram Stories and Meta AI chats on WhatsApp.",
        "body": ["Meta is rolling out Muse Image, its first image generation model from MetaSuperintelligence Labs, inside the Meta AI app. The system uses Muse Spark reasoning to interpret a prompt, search the web for context and plan an image before generating it.", "The launch brings more than 30 new AI-powered effects to Instagram Stories and lets users generate images directly in Meta AI chats on WhatsApp, starting in a handful of countries. Meta plans to expand Muse Image to Facebook, Messenger and more regions in the coming months."],
        "sources": [("9to5Mac", "https://9to5mac.com/2026/07/07/meta-ai-app-adds-image-generation-also-powering-whatsapp-and-instagram-features/")],
    },
    {
        "sub": "Software & Services",
        "h3": "OpenAI ships GPT-Live voice and previews GPT-5.6",
        "summary": "ChatGPT rolled out a new full-duplex GPT-Live voice model and OpenAI previewed its next flagship GPT-5.6 for developers.",
        "body": ["OpenAI launched a new ChatGPT voice experience powered by GPT-Live-1 for paid users and a mini version for free users. The full-duplex design lets the assistant listen and speak at the same time, adding natural back-and-forth speech plus web search, memory and visual widgets.", "The company also previewed GPT-5.6, a new flagship model for developers and enterprises with stronger reasoning and long-horizon agentic capabilities, alongside a public launch planned around July 9. ChatGPT additionally expanded its personal finance features to more US users."],
        "sources": [("OpenAI", "https://openai.com/index/introducing-gpt-live/"), ("Releasebot", "https://releasebot.io/updates/openai/chatgpt")],
    },
    {
        "sub": "Devices & Launches",
        "h3": "Samsung sets July 22 Unpacked for Galaxy Z Fold 8 and Flip 8",
        "summary": "Samsung confirmed a London Unpacked event where it is expected to reveal new foldables, watches and possibly smart glasses.",
        "body": ["Samsung has scheduled its next Galaxy Unpacked event for July 22 in London, livestreamed on YouTube and its website. The company is expected to unveil the Galaxy Z Flip 8 and Galaxy Z Fold 8, with reports pointing to a wider Fold design and a promotion of the top model to Ultra status.", "Alongside the foldables, Samsung may show two new Galaxy Watches and its first smart glasses. Coverage has flagged higher prices this cycle, partly attributed to rising memory costs across the industry."],
        "sources": [("SamMobile", "https://www.sammobile.com/news/samsung-galaxy-unpacked-event-july-22-2026-z-flip-fold-8/"), ("Tom's Guide", "https://www.tomsguide.com/phones/samsung-phones/samsung-galaxy-unpacked-2026-preview-galaxy-z-fold-8-z-flip-8-intelligent-eyewear-and-more")],
    },
    {
        "sub": "Devices & Launches",
        "h3": "Google pushes Gemini Intelligence to Pixel 10 lineup",
        "summary": "Google introduced the Pixel 10 family and began rolling out its rebranded Gemini Intelligence AI features across the new devices.",
        "body": ["Google has launched the Pixel 10, 10 Pro, 10 Pro XL and 10 Pro Fold along with the Pixel Watch 4 and Pixel Buds 2a. The phones run on the new Tensor G5 silicon and ship with the latest Gemini Nano model driving on-device AI features.", "The company is grouping its advanced AI capabilities under the Gemini Intelligence brand, rolling out this summer starting with Pixel 10 and the Galaxy S26. The Pixel Watch adds a Raise to Talk gesture for hands-free Gemini, and the Buds 2a are the first A-series buds with Gemini built in."],
        "sources": [("Google", "https://blog.google/products/gemini/gemini-nano-pixel-10-updates/"), ("9to5Google", "https://9to5google.com/2026/05/12/gemini-intelligence-announcement/")],
    },
    {
        "sub": "EVs & Mobility",
        "h3": "Rivian raises delivery forecast as R2 SUV ramps",
        "summary": "Rivian lifted its 2026 sales guidance after strong early demand for the cheaper R2 SUV that launched last month.",
        "body": ["Rivian raised its full-year delivery forecast to between 65,000 and 70,000 vehicles, up from its earlier range, citing momentum from the R2 SUV that went on sale last month starting near 58,000 dollars. The company expects to sell 20,000 to 25,000 R2 units this year.", "Rivian is also running incentives this month, including 1.99 percent financing on eligible 2026 R1 vehicles and lease deals on the R1T Dual with the large battery. The updated guidance points to a stronger second half as production scales."],
        "sources": [("TechCrunch", "https://techcrunch.com/2026/07/02/rivian-thinks-it-will-sell-more-evs-than-expected-this-year/"), ("InsideEVs", "https://insideevs.com/rivian/")],
    },
    {
        "sub": "Software & Services",
        "h3": "Apple lines up iOS 26.6 update for late July",
        "summary": "Apple is expected to release iOS 26.6 around July 27 with bug fixes as it shifts focus to the major fall software cycle.",
        "body": ["Apple is on track to release iOS 26.6 around Monday, July 27, following its predictable update cadence. The release is expected to focus on bug fixes and under-the-hood changes, typical for an x.6 update as engineering attention moves to the big autumn releases.", "The company has already previewed its next-generation software due in September, including iOS 27 and a macOS release codenamed Golden Gate, which will launch to all users later in the year alongside new iPhone 18 hardware."],
        "sources": [("9to5Mac", "https://9to5mac.com/2026/07/01/ios-26-6-release-date-heres-when-the-new-iphone-update-is-coming/")],
    },
    {
        "sub": "Devices & Launches",
        "h3": "Nothing launches budget Phone (4b) with Glyph design",
        "summary": "Nothing unveiled its first b-series phone, the Phone (4b), bringing its transparent look and Glyph Bar to a lower price point.",
        "body": ["Nothing launched the Phone (4b) on July 7 in a global reveal, the company's first b-series device aimed at the budget segment. Leaks pointed to a Snapdragon 6 Gen 4 chip, 8GB of RAM, a 6.77-inch AMOLED display and a 5,400mAh battery with 45W charging.", "The phone keeps Nothing's signature transparent design and Glyph Bar lighting. The launch comes days after Nothing confirmed its original Phone 1 has received its final software update as the brand shifts attention to newer models."],
        "sources": [("Gizbot", "https://www.gizbot.com/mobile/features/smartphones-launching-in-july-2026-126743.html"), ("Notebookcheck", "https://www.notebookcheck.net/Nothing-s-very-first-smartphone-has-officially-reached-the-end-of-the-road.1334255.0.html")],
    },
    {
        "sub": "Devices & Launches",
        "h3": "Soundcore packs a touchscreen case into Liberty 5 Pro Max buds",
        "summary": "Soundcore's new flagship earbuds add a dedicated AI chip and a 1.78-inch AMOLED touchscreen built into the charging case.",
        "body": ["Soundcore's Liberty 5 Pro Max earbuds use a dedicated AI chip to power Adaptive ANC 4.0 and real-time audio enhancement. The standout feature is the charging case, which includes a 1.78-inch AMOLED touchscreen for adjusting settings and triggering recording without reaching for a phone.", "The launch is part of a busy stretch for premium audio, with Sennheiser's Momentum 5 Wireless headphones and a 650 dollar Sony WH-1000X anniversary edition also arriving around the same window."],
        "sources": [("BGR", "https://www.bgr.com/2195561/cool-new-gadgets-look-out-for-in-june-2026/"), ("TechRadar", "https://www.techradar.com/tech/the-best-tech-of-2026-so-far-the-21-finest-gadgets-weve-tested-this-year")],
    },
    {
        "sub": "Devices & Launches",
        "h3": "Fitbit Air returns Google to screenless fitness bands",
        "summary": "Google's Fitbit Air is a lightweight screenless tracker positioned as a rival to Whoop, weighing just 12 grams.",
        "body": ["Google's Fitbit Air has emerged as one of the more talked-about fitness releases of the year. The screenless band weighs about 12 grams and offers up to a week of battery life, taking direct aim at Whoop-style recovery and sleep tracking wearables.", "The device signals Google's continued push into health hardware under the Fitbit brand, complementing the sensor-heavy Pixel Watch 4 with a simpler always-on band for users who want data without a display."],
        "sources": [("TechRadar", "https://www.techradar.com/tech/the-best-tech-of-2026-so-far-the-21-finest-gadgets-weve-tested-this-year")],
    },
    {
        "sub": "Devices & Launches",
        "h3": "Steam Deck and Switch 2 both hit with price increases",
        "summary": "Valve pushed Steam Deck OLED prices up sharply while Nintendo confirmed a Switch 2 hike coming in September.",
        "body": ["Valve raised Steam Deck prices in late May, with the 512GB OLED climbing to 789 dollars and the 1TB OLED reaching 949 dollars, increases the company tied to rising component costs and logistics pressure. The Deck's verified game library has now passed 25,000 titles.", "Nintendo confirmed the Switch 2 US price will rise from 449.99 to 499.99 dollars effective September 1, though it holds at the lower price through the summer. The console has sold 5.9 million units in the US in its first year, among the fastest starts on record."],
        "sources": [("Nintendo Life", "https://www.nintendolife.com/news/2026/05/valve-follows-switch-2-ps5-and-xbox-with-major-steam-deck-price-hike"), ("Tom's Hardware", "https://www.tomshardware.com/")],
    },
    {
        "sub": "Software & Services",
        "h3": "Netflix begins streaming Spotify video podcasts",
        "summary": "A new Netflix and Spotify deal brings The Bill Simmons Podcast and Ringer sports shows to the streaming platform as video.",
        "body": ["Netflix has struck a deal with Spotify to stream video podcasts, starting with The Bill Simmons Podcast and The Ringer's NFL, NBA, Fantasy Football and F1 shows. Pop culture series like The Rewatchables and Dissect plus true crime titles are also part of the pact.", "The video versions will continue to live on Spotify as well. The tie-up reflects the growing overlap between streaming video and podcasting as both companies chase engagement beyond their core formats."],
        "sources": [("Music Business Worldwide", "https://www.musicbusinessworldwide.com/netflix-inks-spotify-deal-to-stream-video-podcasts-starting-2026/"), ("Netflix Tudum", "https://www.netflix.com/tudum/articles/netflix-spotify-video-podcasts")],
    },
    {
        "sub": "EVs & Mobility",
        "h3": "2026 brings a wave of new and redesigned EVs",
        "summary": "Dozens of new or redesigned electric vehicles are landing across 2026 and 2027, spanning budget models to six-figure off-roaders.",
        "body": ["Automakers are flooding the market with new and redesigned EVs for the 2026 and 2027 model years, with prices ranging from just over 30,000 dollars to well past 100,000. The wave includes budget commuters, three-row family SUVs and rugged off-road models.", "The expanding lineup gives buyers far more choice than a year ago as legacy brands and startups alike broaden their electric ranges. Rivian's R2 is one high-profile arrival, joining a crowded field of family-focused electric SUVs."],
        "sources": [("Cars.com", "https://www.cars.com/articles/heres-every-all-new-or-redesigned-ev-522600/"), ("InsideEVs", "https://insideevs.com/rivian/")],
    },
    {
        "sub": "Software & Services",
        "h3": "Apple maps out 16 new products for later in 2026",
        "summary": "A MacRumors rundown lists a packed Apple hardware pipeline for the back half of the year, led by the iPhone 18 range.",
        "body": ["Apple is lining up as many as 16 new products for release later in 2026, according to a MacRumors overview. The headliners are the iPhone 18 series, including a Pro model with the A20 Pro chip, a smaller Dynamic Island and a new Dark Cherry color.", "Rumors also point to a foldable iPhone Ultra with a 7.7-inch inner display and a Touch ID power button, plus base iPhone 18 and 18e models bumped to 9GB of RAM to keep Apple Intelligence features running smoothly."],
        "sources": [("MacRumors", "https://www.macrumors.com/2026/07/02/apple-to-release-these-16-products-this-year/"), ("Forbes", "https://www.forbes.com/sites/davidphelan/2026/06/15/apple-iphone-18-pro-release-date-september-2026/")],
    },
]
