# -*- coding: utf-8 -*-

AI_HPC = [
    {
        "hero": True,
        "sub": "AI/HPC Stocks & Infrastructure",
        "h3": "Anthropic locks in $19B, 20-year data center lease with TeraWulf",
        "summary": "Anthropic committed to a two-decade, roughly $19 billion lease for about 401 megawatts at TeraWulf's new Kentucky campus, one of the largest AI hosting deals yet.",
        "body": [
            "TeraWulf, the Nasdaq-listed bitcoin miner turned AI infrastructure developer, said Anthropic will anchor its Justified Data campus in Hawesville, Kentucky, under a 20-year agreement worth close to $19 billion. The site covers around 401 megawatts of critical capacity, with phased delivery beginning in the second half of 2027 and full build-out expected by early 2028.",
            "The lease gives Anthropic a large, dedicated block of compute power outside the crowded hyperscaler market and hands TeraWulf a long-dated, investment-grade tenant to underwrite its pivot away from crypto mining. To fund the expansion, TeraWulf agreed to sell its 50.1% stake in the Abernathy joint venture to a group led by development partner Fluidstack, booking a profit on its $450 million investment.",
            "The announcement rippled across the neocloud sector, lifting peers such as IREN, Hut 8, Core Scientific and Riot Platforms as investors read it as fresh evidence of surging demand for purpose-built AI capacity. Shares later gave back some gains even as analysts raised price targets, a sign of how volatile the trade has become.",
        ],
        "sources": [("Data Center Dynamics", "https://www.datacenterdynamics.com/en/news/anthropic-signs-19bn-20-year-lease-for-kentucky-data-center-with-terawulf/"), ("SiliconANGLE", "https://siliconangle.com/2026/07/06/anthropic-inks-19b-ai-data-center-lease-terawulf/")],
    },
    {
        "sub": "AI/HPC Stocks & Infrastructure",
        "h3": "IREN emerges as front-runner for $15B Anthropic capacity deal",
        "summary": "Anthropic is reportedly hunting for at least 1.4 gigawatts of additional data center capacity worth up to $15 billion, with IREN seen as a leading contender for a chunk of it.",
        "body": [
            "Fresh off its TeraWulf lease, Anthropic is said to be pursuing another large tranche of capacity, at least 1.4 gigawatts, in a package that could be valued as high as $15 billion. IREN, which has been aggressively converting mining sites into AI-ready campuses, is viewed as a strong candidate for at least part of the award.",
            "The reports fed a sharp rebound in data center stocks, with IREN jumping double digits in a single session while Applied Digital, TeraWulf and Core Scientific also surged. The moves underscore how tightly the smaller infrastructure names now trade around Anthropic and OpenAI capacity headlines.",
            "For the miners-turned-hosts, landing a multi-year anchor tenant transforms the balance sheet and the valuation multiple. The flip side is concentration risk, since a handful of AI labs are driving nearly all the incremental demand these companies are racing to serve.",
        ],
        "sources": [("24/7 Wall St.", "https://247wallst.com/investing/2026/07/20/iren-soars-14-applied-digital-terawulf-core-scientific-surge-in-a-data-center-rebound/"), ("The Motley Fool", "https://www.fool.com/investing/2026/07/06/why-terawulf-iren-data-center-stocks-up-today/")],
    },
    {
        "sub": "AI/HPC Stocks & Infrastructure",
        "h3": "Nvidia backstops neocloud GPU buys in exchange for revenue share",
        "summary": "Nvidia is helping smaller cloud providers finance huge chip purchases by guaranteeing demand, taking a cut of their cloud revenue in return.",
        "body": [
            "Nvidia has begun acting as a financial backstop for so-called neocloud customers, agreeing to underpin their GPU purchases so they can secure funding, while collecting a share of the resulting cloud revenue. The arrangement lowers the risk for lenders bankrolling capital-intensive AI buildouts.",
            "Early adopters include Firmus, which is deploying around 170,000 GPUs in Batam, Indonesia, and Sharon AI, which is rolling out 40,000 GB300 accelerators. The deals show Nvidia extending its influence deeper into the economics of its own customers.",
            "Critics warn the structure creates circularity, with Nvidia effectively financing demand for its own chips, an issue that has drawn scrutiny as the AI infrastructure boom leans ever more heavily on vendor-supported financing.",
        ],
        "sources": [("Data Center Dynamics", "https://www.datacenterdynamics.com/en/news/nvidia-acts-as-backstop-for-customer-gpus-in-return-for-cut-of-cloud-revenue/")],
    },
    {
        "sub": "AI/HPC Stocks & Infrastructure",
        "h3": "TSMC guides for strong AI demand through the end of the decade",
        "summary": "TSMC told investors it sees robust growth running into 2029 and 2030, a bullish signal for major customers Nvidia, AMD and Broadcom.",
        "body": [
            "Taiwan Semiconductor Manufacturing struck an upbeat tone in its latest update, guiding for full-year revenue growth above 30% and forecasting durable demand for advanced nodes stretching to the end of the decade. The foundry said it would spend near the top of its $52 billion to $56 billion capital budget.",
            "Because Nvidia, AMD and Broadcom all fabricate their most advanced chips at TSMC, the guidance was read as a proxy for the health of the entire AI silicon supply chain and helped steady chip stocks. TSMC also signaled plans to lift chip prices by 5% to 10% starting in 2027.",
            "The confidence comes as the company pours another $100 billion into US manufacturing, reflecting both AI-driven demand and pressure to diversify production away from Taiwan.",
        ],
        "sources": [("The Motley Fool", "https://www.fool.com/investing/2026/07/23/tsmc-incredible-news-nvidia-broadcom-stock/")],
    },
    {
        "sub": "AI/HPC Stocks & Infrastructure",
        "h3": "Hyperscalers on track for $725B in AI infrastructure spending in 2026",
        "summary": "Meta, Microsoft, Amazon and Alphabet are collectively set to spend around $725 billion on AI capacity this year, with Microsoft alone eyeing roughly $190 billion.",
        "body": [
            "The four largest cloud and platform companies are pacing toward a combined $725 billion in AI infrastructure outlays in 2026, a figure that keeps climbing with each earnings cycle. Microsoft expects capital spending of roughly $190 billion for the year, including about $25 billion tied to higher component prices.",
            "Meta lifted its own capex forecast toward $145 billion and told investors it would ramp data center investment significantly, with its first multi-gigawatt cluster, Prometheus, slated to come online during the year. Microsoft said its AI annual revenue run rate topped $37 billion, up more than 120% year over year.",
            "The scale of the commitments has quieted some critics who questioned AI returns, but it also raises the stakes if demand growth ever slows relative to the enormous fixed costs now being locked in.",
        ],
        "sources": [("Data Center Dynamics", "https://www.datacenterdynamics.com/en/news/meta-delivers-blowout-earnings-says-it-will-ramp-ai-data-center-investment-significantly-in-2026/"), ("Global Data Center Hub", "https://www.globaldatacenterhub.com/p/microsoft-q3-fy2026-the-190b-capex")],
    },
    {
        "sub": "Foundation Models & Releases",
        "h3": "Anthropic ships Claude Opus 5, retaking the frontier at half the price",
        "summary": "Claude Opus 5 launched July 24 and immediately topped intelligence and agentic benchmarks while undercutting the prior flagship on price.",
        "body": [
            "Anthropic released Claude Opus 5 on July 24, describing it as a more proactive model that reaches close to the frontier intelligence of Claude Fable 5 at roughly half the cost. It is priced at $5 per million input tokens and $25 per million output tokens, carries a 1M-token context window and a May 2026 knowledge cutoff.",
            "The model debuted at the top of independent leaderboards, including the Artificial Analysis Intelligence Index, and posted standout scores on agentic coding and novel-reasoning tests such as Frontier-Bench and ARC-AGI-3. It became the new default on Claude Max and the strongest option on Claude Pro.",
            "The launch caps an unusually crowded stretch of frontier releases, with Anthropic, OpenAI and xAI all shipping major models within weeks of each other as the labs jockey for the top of the benchmark tables.",
        ],
        "sources": [("Anthropic", "https://www.anthropic.com/news/claude-opus-5"), ("Coursiv", "https://coursiv.io/blog/claude-opus-5")],
    },
    {
        "sub": "Foundation Models & Releases",
        "h3": "Google rolls out Gemini 3.6 Flash as a fast, cheap frontier option",
        "summary": "Google released Gemini 3.6 Flash on July 21, extending its lower-latency line as competition on price and speed intensifies.",
        "body": [
            "Google made Gemini 3.6 Flash available on July 21, its newest fast-tier frontier model aimed at high-volume, latency-sensitive workloads. The Flash line targets developers who want strong reasoning at a fraction of the cost of top-end models.",
            "The release lands in the middle of a dense July model wave, arriving just days before Anthropic's Opus 5 and weeks after OpenAI's GPT-5.6 family and xAI's Grok 4.5. Each lab is pushing hard on the balance between raw capability and cost per token.",
            "For enterprises, the proliferation of capable mid-tier models is steadily driving down the price of usable intelligence, which is reshaping how teams choose between flagship and lightweight tiers for production traffic.",
        ],
        "sources": [("LLM Stats", "https://llm-stats.com/llm-updates"), ("ThursdAI", "https://thursdai.news/releases/2026-07")],
    },
    {
        "sub": "Foundation Models & Releases",
        "h3": "OpenAI's GPT-5.6 family becomes ChatGPT's default",
        "summary": "OpenAI moved its GPT-5.6 lineup of Sol, Terra and Luna into general availability, with the top Sol tier topping several math and reasoning boards.",
        "body": [
            "OpenAI opened its GPT-5.6 family, branded Sol, Terra and Luna, to general availability earlier in July and made it the default across ChatGPT, the API and Codex. The tiers span from a high-end Sol model down to cheaper Terra and Luna options for lighter tasks.",
            "GPT-5.6 Sol claimed the top spot on LiveBench Mathematics and Reasoning and posted a leading score on ARC-AGI-2, cementing OpenAI's position at the front of the pack heading into the late-July releases from rivals.",
            "The staggered pricing across the three tiers reflects a broader industry move toward model families rather than single flagships, letting customers dial capability against cost for each workload.",
        ],
        "sources": [("LLM Stats", "https://llm-stats.com/ai-news"), ("ScriptByAI", "https://www.scriptbyai.com/timeline-of-chatgpt/")],
    },
    {
        "sub": "Foundation Models & Releases",
        "h3": "xAI's Grok 4.5 pushes hard on coding and agentic tasks",
        "summary": "xAI released Grok 4.5 in mid-July as its strongest model yet for coding and autonomous agent workflows, now the default in Grok Build.",
        "body": [
            "xAI launched Grok 4.5 on July 16, positioning it as its most capable model for software development and agentic tasks. It is available through the xAI API and has become the default engine inside the company's Grok Build environment.",
            "The release continued an intense head-to-head with OpenAI, at one point sharing a launch day with the GPT-5.6 rollout, as the two labs trade blows on developer-focused capabilities. Coding and agent performance have become the key battleground for enterprise adoption.",
            "With Grok 4.5, Anthropic's Opus 5, Google's Gemini 3.6 Flash and OpenAI's GPT-5.6 all landing within a single month, developers now have an unusually deep bench of frontier options to benchmark against their own workloads.",
        ],
        "sources": [("NxCode", "https://www.nxcode.io/resources/news/grok-5-release-date-latest-news-2026"), ("Kingy AI", "https://kingy.ai/blog/gpt-5-6-sol-vs-claude-fable-5-vs-grok-4-5-vs-muse-spark-1-1/")],
    },
    {
        "sub": "Chinese AI Ecosystem",
        "h3": "DeepSeek develops its own inference chip to cut Nvidia reliance",
        "summary": "China's DeepSeek is designing an in-house AI chip focused on inference, part of a broader effort to reduce dependence on Nvidia and Huawei silicon.",
        "body": [
            "DeepSeek is working on its own AI processor aimed at inference, the stage where a trained model generates responses, rather than at training new systems. The move would loosen its reliance on Nvidia and Huawei chips that have powered its popular open models.",
            "The effort is still early, with DeepSeek reaching out to chip-design firms, foundries and memory suppliers to line up partners. Building a viable domestic inference chip would give the company more control over cost and supply as export restrictions squeeze access to leading Western hardware.",
            "DeepSeek joins Alibaba and Baidu in developing homegrown accelerators, a trend that is gradually chipping away at Huawei's dominant share of China's roughly $50 billion domestic AI chip market.",
        ],
        "sources": [("Semafor", "https://www.semafor.com/article/07/07/2026/deepseeks-ai-chip-plans"), ("Taipei Times", "https://www.taipeitimes.com/News/biz/archives/2026/07/08/2003860388")],
    },
    {
        "sub": "Chinese AI Ecosystem",
        "h3": "DeepSeek V4 and Alibaba Qwen 3.8 press on frontier US models",
        "summary": "DeepSeek released V4 and Alibaba unveiled Qwen 3.8, both claiming to approach top US systems while undercutting them on price.",
        "body": [
            "China's two leading open-model developers renewed their assault on the frontier, with DeepSeek shipping V4 and Alibaba launching Qwen 3.8. Both companies say the models close much of the gap with the strongest US systems from OpenAI and Anthropic.",
            "Aggressive pricing remains the central strategy, with the Chinese labs offering capable models at a fraction of Western costs to win developers at home and abroad. Alibaba has claimed its latest release surpasses earlier DeepSeek versions on key benchmarks.",
            "The rapid cadence keeps pressure on the open-weight ecosystem globally, where cheap, competitive Chinese models increasingly set the price floor for the rest of the market.",
        ],
        "sources": [("Cybernews", "https://cybernews.com/ai-news/deepseek-and-alibaba-launch-fresh-assaults-on-frontier-ai/"), ("AOL", "https://www.aol.com/news/alibaba-releases-ai-model-claims-051704660.html")],
    },
    {
        "sub": "Chinese AI Ecosystem",
        "h3": "Huawei targets 600,000 Ascend 910C chips as it scales output",
        "summary": "Huawei plans to nearly double production of its flagship Ascend AI chip in 2026, aiming for up to 1.6 million total dies to challenge Nvidia in China.",
        "body": [
            "Huawei is ramping manufacturing of its Ascend 910C accelerator to roughly 600,000 units in 2026, close to double its prior output, and is targeting up to 1.6 million total Ascend dies for the year. State-backed foundry SMIC in Shanghai is a key production partner.",
            "The buildout is central to China's push for semiconductor self-sufficiency and to Huawei's bid to unseat Nvidia in the domestic market, where US export limits have left a wide opening. Huawei already supplies DeepSeek and other major Chinese AI players.",
            "Constraints remain, as Huawei's process technology is stuck at 7 nanometers and its chips trail Nvidia's best on single-chip performance. The company is also leaning on stockpiled foreign high-bandwidth memory amid limited domestic supply.",
        ],
        "sources": [("Yahoo Finance", "https://finance.yahoo.com/news/huaweis-bold-ai-chip-push-180552201.html"), ("MLQ.ai", "https://mlq.ai/news/huawei-plans-massive-production-boost-600000-ascend-910c-ai-chips-to-challenge-nvidia/")],
    },
    {
        "sub": "Chinese AI Ecosystem",
        "h3": "China clarifies export licensing for AI model weights",
        "summary": "China's commerce ministry issued guidance stating that domestically developed model weights, training pipelines and inference infrastructure need licenses before transfer abroad.",
        "body": [
            "China's Ministry of Commerce issued enforcement guidance clarifying that model weights, training pipelines and inference infrastructure built by Chinese companies require export licenses before they can be handed to foreign entities. The move formalizes Beijing's stance that advanced AI artifacts are controlled technology.",
            "The guidance mirrors the logic of Western export regimes, treating trained models and the systems that run them as strategic assets rather than ordinary software. It adds a layer of compliance for Chinese labs that distribute open weights or expand overseas.",
            "The step arrives as the US and EU debate tightening their own controls on advanced AI, signaling that model weights themselves are becoming a contested front in the broader technology standoff.",
        ],
        "sources": [("Cubbbix", "https://cubbbix.com/blog/ai-regulation-july-2026-global-update/")],
    },
    {
        "sub": "Agents & Automation",
        "h3": "OpenAI unveils Presence for enterprise voice and chat agents",
        "summary": "OpenAI launched Presence on July 22, a platform for enterprises to deploy and manage AI agents that can answer questions, take approved actions and escalate to humans.",
        "body": [
            "OpenAI introduced Presence, a product for building and running trusted AI agents across customer-facing and internal workflows. Announced July 22, it bundles company knowledge, standard operating procedures, approved actions, simulations, evaluation tools, guardrails and escalation rules into one system.",
            "At launch Presence supports real-time voice and chat experiences, with marketing hinting at a broader ambition spanning email and other channels. It is available through a limited general availability program rather than self-service, with OpenAI's forward-deployed engineers and select systems integrators leading rollouts.",
            "The launch pushes OpenAI deeper into the enterprise deployment layer, competing directly with orchestration and agent-management vendors as companies look for governed ways to put agents into production.",
        ],
        "sources": [("OpenAI", "https://openai.com/index/introducing-openai-presence/"), ("VentureBeat", "https://venturebeat.com/orchestration/openai-unveils-presence-a-new-platform-that-lets-enterprises-launch-and-manage-realtime-voice-agents-and-chatbots")],
    },
    {
        "sub": "Agents & Automation",
        "h3": "OpenAI's ChatGPT Work brings agents that run business workflows",
        "summary": "OpenAI expanded its enterprise push with ChatGPT Work, pairing autonomous agents and Codex to execute multi-step tasks inside company systems.",
        "body": [
            "Alongside Presence, OpenAI has been building out ChatGPT Work, an enterprise offering centered on agents that can carry out full workflows rather than just answer prompts. The effort ties together ChatGPT's assistant features with Codex-driven automation for technical tasks.",
            "The pitch is to move enterprises from chat assistants toward agents that act inside internal tools, complete approved actions and hand off to people when needed. It reflects a wider shift in which the value proposition is task completion, not conversation.",
            "The releases sharpen OpenAI's enterprise strategy at a moment when rivals are racing to own the layer where agents are deployed, governed and measured across large organizations.",
        ],
        "sources": [("Enterprise DNA", "https://enterprisedna.co/resources/news/openai-chatgpt-work-enterprise-agents-codex-july-2026/"), ("OpenAI", "https://openai.com/index/next-phase-of-enterprise-ai/")],
    },
    {
        "sub": "Agents & Automation",
        "h3": "Huawei Cloud opens beta of CodeArts autonomous coding agent",
        "summary": "Huawei began open beta testing of CodeArts Agent, a coding assistant that blends IDE features with autonomous, project-level development, as it expands agentic infrastructure into Thailand.",
        "body": [
            "Huawei Cloud started open beta testing of CodeArts Agent, a coding tool that mixes traditional IDE assistance with more autonomous capabilities such as project-level code generation, code completion, engineering knowledge Q&A and unit-test creation. The launch accompanied the debut of Huawei's agentic infrastructure offering in Thailand.",
            "The move signals Huawei's intent to compete in the fast-growing coding-agent category, where the frontier is shifting from autocomplete toward agents that can plan and execute larger chunks of development work. It also extends Huawei's cloud footprint across Southeast Asia.",
            "Coding remains the sharpest proving ground for agentic AI, and Huawei's entry adds a major non-Western player to a field crowded with offerings from OpenAI, Anthropic and a wave of startups.",
        ],
        "sources": [("AI Agent Store", "https://aiagentstore.ai/ai-agent-news/this-week")],
    },
    {
        "sub": "Agents & Automation",
        "h3": "Alterion's Draco adds runtime governance for enterprise agents",
        "summary": "Startup Alterion launched Draco, a runtime control platform that gives security and compliance teams visibility and enforcement over AI agents across clouds and vendors.",
        "body": [
            "Alterion introduced Draco, a runtime control layer designed to give security, risk and compliance leaders oversight of enterprise AI agents. The platform enforces governance across different clouds, model vendors and endpoints as agents operate in production.",
            "The product targets a growing pain point, since companies deploying autonomous agents increasingly need to monitor what those agents do, constrain their actions and prove compliance. Draco aims to sit between agents and the systems they touch to apply policy in real time.",
            "The launch reflects an emerging category of agent governance tooling that is forming around the deployment boom, as enterprises worry more about control and auditability than raw capability.",
        ],
        "sources": [("Agentic.ai", "https://agentic.ai/news")],
    },
    {
        "sub": "Agents & Automation",
        "h3": "Google moves agentic threat-intelligence tools to general availability",
        "summary": "Google Threat Intelligence made its agentic security capabilities generally available, automating threat hunting, incident response and alert triage for enterprise customers.",
        "body": [
            "Google promoted its agentic AI capabilities within Google Threat Intelligence to general availability for Enterprise and Enterprise+ customers. The tools are built to automate labor-intensive defensive work including threat hunting, incident response and daily alert triage.",
            "Security operations has become one of the most concrete near-term uses for agents, where the volume of alerts and the shortage of skilled analysts make automation attractive. Google is positioning its agents to shoulder repetitive investigation work so human teams can focus on the hardest cases.",
            "The rollout adds to a busy stretch of enterprise agent launches, underscoring how quickly cybersecurity has become a flagship deployment area for autonomous AI systems.",
        ],
        "sources": [("AI Agent Store", "https://aiagentstore.ai/ai-agent-news/this-week")],
    },
    {
        "sub": "Enterprise & Regulation",
        "h3": "EU AI Act August 2 deadline nears amid Digital Omnibus delays",
        "summary": "A key EU AI Act enforcement milestone lands on August 2, even as a spring Digital Omnibus deal pushed back several high-risk obligations.",
        "body": [
            "The EU AI Act is approaching an August 2 enforcement checkpoint, one of the staggered deadlines that phase in the bloc's landmark rules. A provisional Digital Omnibus agreement reached in spring 2026 deferred several high-risk obligations, giving use-based high-risk systems extra time beyond the original schedule.",
            "The delays reflect ongoing friction between regulators pushing to implement the law and industry groups warning that compliance burdens could slow European AI development. Companies operating in the EU are still working to map their systems to the Act's risk tiers.",
            "For US firms with European exposure, the approaching deadline is forcing decisions about documentation, transparency and governance even as the broader timeline keeps shifting.",
        ],
        "sources": [("Cubbbix", "https://cubbbix.com/blog/ai-regulation-july-2026-global-update/"), ("Collibra", "https://www.collibra.com/blog/ai-regulatory-compliance-in-2026-eu-ai-act-us-orders-and-state-laws-and-how-to-operationalize")],
    },
    {
        "sub": "Enterprise & Regulation",
        "h3": "US federal preemption fight over AI rules intensifies",
        "summary": "With no comprehensive federal AI law, a fight is heating up over whether Washington should preempt the growing patchwork of state AI regulations.",
        "body": [
            "The US still lacks comprehensive federal AI legislation, leaving policy to a mix of executive orders, voluntary frameworks such as the NIST AI Risk Management Framework and sector guidance from agencies like the FDA, FTC and FINRA. Into that vacuum, states have moved with their own rules.",
            "The result is an escalating preemption battle over whether federal action should override state AI laws to create a single national standard. Industry generally favors preemption to avoid a fragmented compliance landscape, while some states want to preserve their own protections.",
            "The uncertainty complicates planning for enterprises, which must hedge against divergent requirements across jurisdictions while Washington debates the shape of any national framework.",
        ],
        "sources": [("MetricStream", "https://www.metricstream.com/blog/ai-regulation-trends-ai-policies-us-uk-eu.html"), ("Cubbbix", "https://cubbbix.com/blog/ai-regulation-july-2026-global-update/")],
    },
    {
        "sub": "Enterprise & Regulation",
        "h3": "Few enterprises have scaled AI agents despite broad experimentation",
        "summary": "McKinsey research finds nearly two-thirds of enterprises have piloted AI agents but fewer than 10% have scaled them to measurable value, citing data and governance gaps.",
        "body": [
            "New McKinsey research paints a sober picture of enterprise agent adoption, finding that while close to two-thirds of companies have experimented with AI agents, fewer than one in ten have scaled them to deliver measurable value. The gap between pilots and production remains wide.",
            "The main barriers are poor data quality and weak governance rather than model capability, according to the findings. Organizations struggle to feed agents reliable data and to put controls around what agents are allowed to do once deployed.",
            "The results help explain the surge of agent governance and runtime control products hitting the market, as vendors race to solve the operational problems that keep promising pilots from reaching scale.",
        ],
        "sources": [("Northflank", "https://northflank.com/blog/enterprise-ai-coding-agent-deployment")],
    },
    {
        "sub": "Enterprise & Regulation",
        "h3": "Microsoft's AI revenue tops $37B run rate as component costs bite",
        "summary": "Microsoft said its AI business surpassed a $37 billion annual run rate, up more than 120% year over year, even as rising component prices lift its capex bill.",
        "body": [
            "Microsoft disclosed that its AI annual revenue run rate crossed $37 billion, growing more than 120% from a year earlier, a sign that monetization is beginning to catch up with the company's enormous infrastructure spend. The figure spans Azure AI services and Copilot-driven products.",
            "The growth comes as Microsoft guides toward roughly $190 billion in 2026 capital spending, including about $25 billion attributable to higher component pricing. Memory and other supply constraints are pushing up the cost of building AI capacity across the industry.",
            "The numbers frame the central enterprise-AI question of the moment, whether revenue can scale fast enough to justify the historic sums the hyperscalers are committing to data centers and chips.",
        ],
        "sources": [("Global Data Center Hub", "https://www.globaldatacenterhub.com/p/microsoft-q3-fy2026-the-190b-capex"), ("Stocktwits", "https://stocktwits.com/news-articles/markets/equity/microsoft-meta-and-google-just-silenced-ai-spending-critics-in-one-earnings-night-as-big-tech-capex-swells-to-725-b/cZBtCIgReEx")],
    },
]
