# -*- coding: utf-8 -*-
CRYPTO_MACRO = [
    {
        "hero": True,
        "sub": "Macro & Central Banks",
        "h3": "US strikes on Iran roil markets, oil jumps as ceasefire declared over",
        "summary": "President Trump said the US-Iran understanding was over after a second day of strikes, sending Brent crude up more than 5 percent and pressuring risk assets.",
        "body": ["US forces carried out powerful strikes against Iranian targets late Tuesday in response to attacks on three commercial vessels in the Strait of Hormuz, and Trump declared the interim peace deal over while speaking in Ankara ahead of a NATO summit. Brent crude jumped 5.2 percent to settle around 78.02 dollars as traders feared renewed disruption to shipping through Hormuz.", "US equities finished mixed on Wednesday. The Dow fell roughly 1 percent or more than 500 points, the S&P 500 slipped about 0.2 percent, and the Nasdaq trimmed losses to gain 0.2 percent. Prices eased off session lows after Trump said he did not think the US and Iran would return to full-scale war."],
        "sources": [("TheStreet", "https://www.thestreet.com/stock-market-today/stock-market-today-dow-jones-sp-500-nasdaq-updates-july-8-2026"), ("CNBC", "https://www.cnbc.com/2026/07/08/oil-prices-brent-wti-iran-us-hormuz.html")],
    },
    {
        "sub": "Macro & Central Banks",
        "h3": "Fed seen holding at July 29 meeting after weak jobs data",
        "summary": "Markets put roughly 78 percent odds on the Fed leaving rates at 3.50 to 3.75 percent, with only a 22 percent chance of a hike, after a soft payrolls report.",
        "body": ["Under Chair Kevin Warsh the Fed held its target range at 3.50 to 3.75 percent in June, and CME FedWatch data now shows a 78.1 percent probability of another hold on July 29 against 21.9 percent odds of a hike. A weaker jobs report and Warsh's guarded comments at the ECB forum in Sintra cooled hike expectations, according to Barclays.", "Warsh has struck a more hawkish tone on inflation, lifting the 2026 PCE projection to 3.6 percent from 2.7 percent and signaling concern that price pressures may prove sticky. The Middle East energy shock adds a fresh upside risk to that outlook."],
        "sources": [("Intellectia", "https://intellectia.ai/blog/fed-interest-rate-decision-july-2026"), ("CNBC", "https://www.cnbc.com/2026/06/17/fed-interest-rate-decision-june-2026.html")],
    },
    {
        "sub": "Macro & Central Banks",
        "h3": "US payrolls rose just 57,000 in June, well below forecasts",
        "summary": "June hiring badly missed the 115,000 consensus, and the jobless rate fell to 4.2 percent only because the labor force shrank.",
        "body": ["Nonfarm payrolls climbed 57,000 in June, down from a revised 129,000 in May and short of the 115,000 expected. April and May were revised down by a combined 74,000. Leisure and hospitality shed 61,000 jobs while professional and business services added 36,000.", "The unemployment rate dipped to 4.2 percent as participation fell 0.3 point to 61.5 percent, the lowest since March 2021, with 507,000 fewer people reported at work. Traders eased bets on a near-term rate increase after the release."],
        "sources": [("CNBC", "https://www.cnbc.com/2026/07/02/jobs-report-june-2026-.html"), ("Yahoo Finance", "https://finance.yahoo.com/economy/articles/u-jobs-report-june-2026-123456841.html")],
    },
    {
        "sub": "Macro & Central Banks",
        "h3": "ECB set to weigh another hike on July 23 as energy risks build",
        "summary": "After a June quarter-point increase, the Governing Council meets July 23 with hawks eyeing a further move if Middle East energy prices reignite inflation.",
        "body": ["The ECB raised its three key rates 25 basis points in June, lifting the deposit rate to 2.25 percent, and will announce its next decision on Thursday July 23 with a Lagarde press conference to follow. July is not a projection meeting, so only the policy statement will be published.", "The council must judge whether the June move was enough or whether hawks from Germany, the Netherlands and Austria push for more as Hormuz energy dynamics and second-round wage effects shape the eurozone outlook."],
        "sources": [("ECB", "https://www.ecb.europa.eu/press/pr/date/2026/html/ecb.mp260611~4d41bd5e83.en.html"), ("Finance Calendar", "https://www.financecalendar.com/event/ecb-rate-decision-july-2026/")],
    },
    {
        "sub": "Macro & Central Banks",
        "h3": "Gold slides to 4,050 dollars as Iran deal collapse revives rate fears",
        "summary": "Gold fell more than 1 percent to its lowest since July 2 after the Iran peace deal broke down, with markets now pricing at least one more Fed hike this year.",
        "body": ["Gold dropped to about 4,050 dollars an ounce Wednesday, its weakest since July 2, as the collapse of the US-Iran understanding pushed oil up more than 5 percent and stoked fears of inflation and higher rates. The metal hit a record 5,595 dollars in late January but has since suffered its worst quarterly decline since 2013.", "Rising bond yields, a firmer dollar and renewed appetite for tech stocks have weighed on bullion, even as China's central bank posted its biggest monthly gold reserve increase in more than two and a half years in June."],
        "sources": [("Trading Economics", "https://tradingeconomics.com/commodity/gold"), ("MoneyMagpie", "https://www.moneymagpie.com/investment-articles/gold-price-prediction-july-2026")],
    },
    {
        "sub": "Bitcoin & Ethereum",
        "h3": "Bitcoin drops toward 62K as Middle East strikes hit risk assets",
        "summary": "Bitcoin traded near 62,000 dollars on Wednesday, down about 1 percent on the day, as renewed US-Iran hostilities dented appetite for risk.",
        "body": ["Bitcoin opened at 63,318 dollars on July 8 and slid to roughly 62,000 by mid-morning, down about 1.1 percent from Tuesday, tracking a broader risk-off move tied to the US strikes on Iran. The token has given back most of its 2026 gains, with year-to-date performance cut to low single digits.", "Both bitcoin and ether fell alongside equities as oil prices surged, underscoring how tightly crypto is trading with macro and geopolitical headlines this week."],
        "sources": [("Yahoo Finance", "https://finance.yahoo.com/personal-finance/investing/article/bitcoin-and-ethereum-prices-today-wednesday-july-8-2026-crypto-prices-down-following-us-iran-strikes-130336886.html"), ("Fortune", "https://fortune.com/article/price-of-bitcoin-07-08-2026/")],
    },
    {
        "sub": "Bitcoin & Ethereum",
        "h3": "Ether slumps near 1,740 dollars with sentiment in extreme fear",
        "summary": "Ethereum traded around 1,740 dollars on July 8, off about 31 dollars on the day, as the Fear and Greed Index collapsed to a reading of 20.",
        "body": ["ETH changed hands near 1,743 dollars on July 8, with analysts flagging critical support at 1,716 and the 200-hour EMA around 1,724 acting as an intraday floor. Short-term momentum is bearish and market cap sits around 233 billion dollars, keeping ether the second-largest crypto asset.", "Sentiment has collapsed to Extreme Fear, a reading of 20, reflecting the risk-off tone across markets after the Iran flare-up."],
        "sources": [("Cryptonomist", "https://en.cryptonomist.ch/2026/07/08/ethereum-price-analysis-bearish-july-2026/"), ("Fortune", "https://fortune.com/article/price-of-ethereum-07-08-2026/")],
    },
    {
        "sub": "Bitcoin & Ethereum",
        "h3": "Bitcoin ETFs snap 10-day outflow streak with 222 million haul",
        "summary": "US spot bitcoin ETFs pulled in 221.7 million dollars on July 2, their largest daily inflow in two months, ending a 2.7 billion dollar, 10-day exodus.",
        "body": ["After eight straight weeks of outflows, spot bitcoin ETFs saw 221.72 million dollars of inflows on July 2, breaking a 10-day, 2.7 billion dollar outflow streak that followed a brutal June of more than 4 billion in redemptions. Year-to-date net outflows still stand at about 5.4 billion.", "IBIT bled cash across all four sessions from June 29 to July 2, while Fidelity's FBTC and ARK 21Shares' ARKB drew inflows of 166 million and 91.8 million dollars. Institutional ownership has risen to about 38 percent of assets from 24 percent a year earlier."],
        "sources": [("KuCoin", "https://www.kucoin.com/news/flash/u-s-spot-bitcoin-etfs-record-527m-net-outflows-from-june-29-to-july-2"), ("Tech Times", "https://www.techtimes.com/articles/319653/20260703/bitcoin-etf-outflow-streak-ends-27b-june-jobs-data-cools-rate-risk.htm")],
    },
    {
        "sub": "Bitcoin & Ethereum",
        "h3": "Bitcoin miner ETF up 48 percent even as MicroStrategy craters",
        "summary": "The CoinShares Valkyrie Bitcoin Miners ETF has gained 47.58 percent year to date, while Strategy, formerly MicroStrategy, is down about 34 percent.",
        "body": ["The actively managed WGMI miner ETF, which holds companies deriving at least half their revenue from mining, is up 47.58 percent through July 6 despite bitcoin slipping, deliberately avoiding MicroStrategy-style treasury plays. It captures the picks-and-shovels side of the industry.", "Strategy, the world's largest corporate bitcoin holder, is down 33.68 percent year to date and more than 75 percent over the past year, closing July 6 at 100.77 dollars after a Q1 net loss of 12.54 billion under fair-value accounting."],
        "sources": [("Yahoo Finance", "https://finance.yahoo.com/markets/crypto/articles/bitcoin-miners-etf-47-58-173306970.html"), ("24/7 Wall St.", "https://247wallst.com/investing/etf/2026/07/07/bitcoin-miners-etf-up-47-58-this-year-completely-avoids-microstrategy/")],
    },
    {
        "sub": "Bitcoin & Ethereum",
        "h3": "Strategy sold 3,588 BTC to fund preferred stock payouts",
        "summary": "Michael Saylor's Strategy sold about 216 million dollars of bitcoin between June 29 and July 5 to fund distributions and rebuild its cash reserve.",
        "body": ["Strategy sold 3,588 bitcoin for roughly 216 million dollars in the week ending July 5, using proceeds to pay distributions on its STRC preferred stock and replenish its USD reserve. The firm still holds 843,775 BTC plus about 2.55 billion dollars in cash, keeping it the largest corporate treasury.", "The sale is notable because Strategy has historically been a relentless buyer, and it comes as the stock trades near multi-year lows amid heavy unrealized bitcoin losses."],
        "sources": [("CryptoSlate", "https://cryptoslate.com/strategy-faces-8-3-billion-bitcoin-q2-loss-as-saylor-sells-over-200m-in-btc/"), ("Bitbo", "https://bitbo.io/treasuries/microstrategy")],
    },
    {
        "sub": "DeFi & Altcoins",
        "h3": "Altcoins defy bitcoin, XRP and Solana notch weekly gains",
        "summary": "Capital rotated into higher-risk tokens as XRP and Solana rallied, with Sui, Bittensor and Shiba Inu up 14 to 17 percent on the week.",
        "body": ["Analysts described a classic rotation pattern as XRP rose nearly 10 percent and Solana about 7 percent over the week even as bitcoin's year-to-date gain halved to 4 percent. Sui, Bittensor and Shiba Inu posted gains between 14 and 17 percent in the same stretch.", "The move was fueled by sustained Solana ETF inflows and speculation about a potential XRP ETF approval, with XRP-linked funds adding 59.4 million dollars in June, a third straight month of net inflows."],
        "sources": [("Decrypt", "https://decrypt.co/354116/altcoins-defy-bitcoin-slump-xrp-solana-double-digit-gains"), ("CoinDesk", "https://www.coindesk.com/daybook-us/2026/07/01/xrp-hype-funds-are-the-bright-spots-as-investors-flee-bitcoin-ether-etfs")],
    },
    {
        "sub": "DeFi & Altcoins",
        "h3": "SOL near 77 dollars, XRP at 1.08 as majors trade lower",
        "summary": "Solana slipped about 5 percent to 77 dollars and XRP fell nearly 4 percent to 1.08 on July 8, tracking the broader risk-off tone.",
        "body": ["Solana traded around 77.06 dollars on July 8, down 5.2 percent on the day, while XRP sat at 1.08 dollars, off 3.9 percent, as the Iran-driven sell-off dragged on altcoins. The pullback followed a week of outperformance versus bitcoin.", "Clearstream added SOL to its regulated custody service the same day, and an analyst reiterated a 150 dollar SOL target citing reduced exchange outflows and improving technicals."],
        "sources": [("24/7 Wall St.", "https://247wallst.com/investing/cryptocurrency/2026/07/08/can-solana-sol-outpace-xrp-ripple-in-crypto-rankings/"), ("CoinMarketCap", "https://coinmarketcap.com/cmc-ai/solana/latest-updates/")],
    },
    {
        "sub": "DeFi & Altcoins",
        "h3": "XRP Ledger v3.2.0 upgrade clears validator milestone",
        "summary": "More than 55 percent of trusted XRP Ledger validators are now running the v3.2.0 release, bringing infrastructure and security improvements.",
        "body": ["The XRP Ledger's v3.2.0 upgrade passed a key threshold with over 55 percent of trusted validators running the new software, a step toward activating its amendments. The release adds infrastructure improvements, security fixes and developer enhancements.", "The progress feeds an active build cycle around the ledger as XRP-focused funds continue to draw inflows and ETF speculation persists."],
        "sources": [("Cryptonews", "https://cryptonews.com/news/xrp-price-prediction-validator-upgrade/"), ("CoinDesk", "https://www.coindesk.com/")],
    },
    {
        "sub": "DeFi & Altcoins",
        "h3": "Staking ETFs emerge as US market embraces ether yield",
        "summary": "SEC filings show staking products entering the US ETF structure, though steep fees may blunt the yield reaching investors.",
        "body": ["Grayscale's March filing for its Ethereum Staking Mini ETF disclosed more than 861,000 ETH and 8.375 million dollars in staking reward income for the quarter ended March 31. BlackRock's staked ether trust filing set an aggregate staking fee at 18 percent of gross staking consideration.", "With ETH staking yields near 2.6 to 3.0 percent, analysts caution the combination of staking cuts and management fees may leave investors with a modest rather than transformative income stream."],
        "sources": [("TECHi", "https://www.techi.com/ethereum-etf-staking-sec-decision/"), ("Bitcoin Foundation", "https://bitcoinfoundation.org/news/crypto-etfs-news/ethereum-etf-update-could-staking-etfs-become-eths-biggest-catalyst/")],
    },
    {
        "sub": "Regulation & Policy",
        "h3": "SEC puts crypto atop agenda, Regulation Crypto proposal due in July",
        "summary": "The SEC released its 2026 regulatory agenda on July 7, teeing up a crypto rulemaking that would create safe harbors for DeFi and tokenized securities.",
        "body": ["The SEC's agenda, released July 7, places digital assets among its highest near-term priorities, with a Regulation Crypto proposal expected as soon as this month followed by a public comment period. The plan would establish safe harbors and exemptions for on-chain activity including DeFi and tokenized securities.", "Under the draft, eligible startups valued under 5 million dollars in their first four years could raise up to 75 million via qualifying crypto investment contracts, complementing the agency's earlier interpretive guidance on when tokens are securities."],
        "sources": [("Cryptonomist", "https://en.cryptonomist.ch/2026/07/08/sec-crypto-safe-harbor-july/"), ("SEC", "https://www.sec.gov/newsroom/press-releases/2026-30-sec-clarifies-application-federal-securities-laws-crypto-assets")],
    },
    {
        "sub": "Regulation & Policy",
        "h3": "Strategic Bitcoin Reserve stalls in Treasury-Commerce turf war",
        "summary": "More than 16 months after Trump's executive order, the US still has not named a managing agency or bought a single new satoshi.",
        "body": ["A Bloomberg report says the reserve is stuck over which department should house it, with Treasury and Commerce fighting for control of roughly 328,372 seized BTC worth about 25 billion dollars. The DOJ Office of Legal Counsel is reviewing which agency can legally manage the trove.", "Officials are also weighing whether the government can hold volatile bitcoin indefinitely, and Congress has not advanced the legislation White House advisers say is needed to formalize the plan."],
        "sources": [("CoinDesk", "https://www.coindesk.com/policy/2026/07/06/bitcoin-s-u-s-reserve-still-a-work-in-progress-as-federal-agencies-hash-it-out"), ("Bitcoin.com", "https://news.bitcoin.com/strategic-bitcoin-reserve-treasury-commerce-turf-war/")],
    },
    {
        "sub": "Regulation & Policy",
        "h3": "GENIUS Act stablecoin rules face July 18 deadline",
        "summary": "Regulators must finalize capital, liquidity and supervision rules for payment stablecoins by July 18 or the framework still activates in January 2027.",
        "body": ["The July 18 statutory deadline could bring clarity to the roughly 310 billion dollar stablecoin market, unlocking institutional flows if regulators finalize comprehensive rules for permitted payment stablecoin issuers. If they miss it, the GENIUS Act still takes effect January 18, 2027.", "FinCEN and OFAC proposed AML and sanctions rules for issuers in April with a June 9 comment deadline, and global regimes from MiCA to Singapore's MAS framework are converging on full-reserve backing and clear redemption rights."],
        "sources": [("BlockEden", "https://blockeden.xyz/blog/2026/02/08/genius-act-stablecoin-deadline-july-2026-occ-rulemaking/"), ("BVNK", "https://bvnk.com/blog/global-stablecoin-regulations-2026")],
    },
    {
        "sub": "Regulation & Policy",
        "h3": "Clarity Act faces August deadline to survive the Senate",
        "summary": "The House-passed Digital Asset Market Clarity Act needs Senate passage by August or its odds of becoming law this year collapse before the midterms.",
        "body": ["The House passed H.R. 3633, the Digital Asset Market Clarity Act, in July 2025 to overhaul crypto market regulation, and the Senate Banking Committee released its own draft in January 2026. Stakeholders warn that if the bill does not clear the Senate by August 2026, the midterm calendar effectively kills it for the year.", "The SEC's interpretive guidance on crypto assets is meant to complement, not replace, a statutory market-structure framework that would divide oversight between the SEC and CFTC."],
        "sources": [("Congress.gov", "https://www.congress.gov/crs-product/LSB11415"), ("DL News", "https://www.dlnews.com/articles/regulation/key-dates-for-us-crypto-regulation-in-2026/")],
    },
]

MENTAL_HEALTH = [
    {
        "hero": True,
        "sub": "Research & Studies",
        "h3": "APA survey: a third of psychologists have patients bringing AI to therapy",
        "summary": "More than a third of psychologists report patients using AI chatbots as a supplemental mental health resource, according to the APA's 2026 survey.",
        "body": ["The APA's 2026 Chatbots and Mental Health Survey found more than a third of psychologists have patients turning to AI to supplement care from licensed professionals. A November 2025 poll found 12 percent of US adults said they were likely to use AI chatbots for mental health support within six months.", "The APA warns these tools remain inconsistently regulated on safety and privacy, and that every study comparing chatbots to human therapists for moderate-to-severe anxiety or depression shows clinicians produce significantly better outcomes."],
        "sources": [("APA", "https://www.apa.org/pubs/reports/chatbots-mental-health-2026"), ("Simply Psychology", "https://www.simplypsychology.com/articles/ai-therapy-chatbots-research-review")],
    },
    {
        "sub": "Research & Studies",
        "h3": "Studies flag chatbots as a mental health risk to teens",
        "summary": "New research warns that heavy chatbot use can drive relational displacement, dependency and social withdrawal among adolescents.",
        "body": ["Researchers describe relational displacement, where teens substitute AI chats for human conversation, potentially stunting the relationship skills that guard against depression, anxiety and loneliness. Emerging evidence also flags dependency, social withdrawal and privacy concerns.", "The stakes are high because multiple lawsuits have alleged that AI chatbots contributed to teen suicides, meaning even rare safety failures can be devastating when millions of young people rely on the tools."],
        "sources": [("Ashe Post & Times", "https://www.ashepostandtimes.com/news/national/study-warns-chatbots-pose-mental-health-risk-to-teens/article_2561abaa-3981-5e53-b571-d2831d3137f3.html"), ("Scientific American", "https://www.scientificamerican.com/article/teen-ai-chatbot-usage-sparks-mental-health-and-regulation-concerns/")],
    },
    {
        "sub": "Research & Studies",
        "h3": "LLMs misjudge suicide risk versus expert clinicians",
        "summary": "Research comparing ChatGPT, Claude and Gemini with clinicians found the models often misalign with expert risk assessments, sometimes downplaying the most acute cases.",
        "body": ["A study published in Psychiatric Services evaluated whether leading chatbots gave direct responses to suicide-related queries and how those responses tracked clinician-assigned risk levels. Separate work on veteran vignettes found generative models rated the most acute case as less severe and the least acute case as more severe than providers did.", "Stanford researchers have also shown that low-cost LLM therapy chatbots can introduce biases and failures with potentially dangerous consequences, reinforcing that the tools cannot reliably detect psychiatric emergencies."],
        "sources": [("Psychiatric Services", "https://psychiatryonline.org/doi/10.1176/appi.ps.20250086"), ("Stanford Report", "https://news.stanford.edu/stories/2025/06/ai-mental-health-care-tools-dangers-risks")],
    },
    {
        "sub": "Research & Studies",
        "h3": "AI app PATH cut anxiety and depression in UK trial",
        "summary": "A randomized trial of the AI-powered app PATH with 316 UK participants found reductions in symptoms versus an NHS self-help control.",
        "body": ["The study, published in the Journal of Affective Disorders in May 2026, randomized 316 UK-based participants to either PATH or a control group using an NHS self-help website, adding to evidence that AI apps can move the needle on anxiety and depression. Results were highlighted as compelling support for the category.", "The trial joins a wider body of work including the Therabot generative-AI trial and earlier Woebot studies, though researchers stress effect sizes and durability still need larger confirmation."],
        "sources": [("Forbes", "https://www.forbes.com/sites/lanceeliot/2026/03/23/new-empirical-study-provides-compelling-evidence-that-ai-mental-health-apps-can-reduce-anxiety-and-depression/"), ("NEJM AI", "https://ai.nejm.org/doi/full/10.1056/AIoa2400802")],
    },
    {
        "sub": "Research & Studies",
        "h3": "Harvard asks whether AI therapy at scale is safe",
        "summary": "With millions already using AI for therapy, Harvard Medicine examines the gap between demand for care and the safety of unregulated tools.",
        "body": ["The Harvard Medicine feature notes AI chatbots are filling a gap left by a shortage of human providers, but warns the tools cannot reliably detect suicidal ideation or handle crises. It frames accessibility as the main draw and safety as the main unresolved risk.", "Adversarial research probing how chatbots behave under distress scenarios is now being used to generate design guidance for relational safety."],
        "sources": [("Harvard Medicine", "https://magazine.hms.harvard.edu/articles/millions-already-turn-ai-therapy-it-safe"), ("arXiv", "https://arxiv.org/abs/2602.22775")],
    },
    {
        "sub": "Tools & Applications",
        "h3": "STAT News: teens need rules before chatbots become their therapist",
        "summary": "A STAT News commentary argues policymakers must set guardrails as teens increasingly turn to chatbots for mental health help.",
        "body": ["The July 2 STAT piece calls for rules rather than outright bans as adolescents lean on chatbots for emotional support, warning that leaving the space unregulated invites harm. It stresses detection of self-harm signals and clear referral pathways as minimum safeguards.", "The argument lands amid a wave of state action and lawsuits, positioning teen safety as the central policy question for AI mental health tools in 2026."],
        "sources": [("STAT News", "https://www.statnews.com/2026/07/02/teens-chatbots-mental-health-rules-bans/"), ("Psychiatric Times", "https://www.psychiatrictimes.com/view/protecting-children-from-chatbot-companions")],
    },
    {
        "sub": "Tools & Applications",
        "h3": "Connecticut and California push AI companion chatbot rules",
        "summary": "New state laws require chatbot operators to detect self-harm signals and route users to crisis resources such as the 988 lifeline.",
        "body": ["Connecticut now requires AI chatbot operators to make reasonable efforts to detect suicidal ideation or self-harm and to respond with appropriate resources. States including California, Georgia, Idaho, Iowa, Nebraska, New York, Oregon and Washington have advanced similar companion-chatbot legislation.", "California's SB 243 requires operators to maintain suicide-prevention protocols with crisis referrals, post public notices and report annually to the Office of Suicide Prevention, setting an early template for the sector."],
        "sources": [("CT Governor", "https://portal.ct.gov/governor/news/press-releases/2026/06-2026/governor-lamont-signs-legislation-establishing-youth-online-safety-protections"), ("Troutman", "https://www.troutmanprivacy.com/2026/01/analyzing-the-new-ai-companion-chatbot-laws/")],
    },
    {
        "sub": "Tools & Applications",
        "h3": "FDA weighs oversight of generative AI mental health devices",
        "summary": "After a November advisory meeting on generative-AI mental health devices, the FDA is working to clarify which products need premarket review.",
        "body": ["The FDA held its second Digital Health Advisory Committee meeting on generative-AI mental health devices in November 2025 and is drafting clearer rules, treating general wellness apps as outside its remit while focusing on tools that provide therapy for specific disorders. Its TEMPO pilot began collecting statements of interest in January 2026.", "CMS separately expanded digital mental health treatment codes to cover ADHD digital therapeutics effective in 2026, widening reimbursement pathways for the category."],
        "sources": [("Sidley Austin", "https://www.sidley.com/en/insights/newsupdates/2025/11/us-fda-and-cms-actions-on-generative-ai-enabled-mental-health-devices-yield-insights-across-ai"), ("npj Mental Health Research", "https://www.nature.com/articles/s44184-025-00174-2")],
    },
    {
        "sub": "Tools & Applications",
        "h3": "AI mental health market consolidates around Wysa and enterprise players",
        "summary": "The 2026 landscape is coalescing around clinically backed platforms like Wysa as Woebot exits consumer, with Slingshot AI's Ash among newer entrants.",
        "body": ["Wysa has become the largest global player in conversational mental health support, holding ISO 13485 and SOC 2 certifications and integrating with the NHS and large employer programs, and it acquired April Health and Kins in 2025. Woebot shifted to an enterprise-only model after winding down its consumer app.", "Newer entrants such as Slingshot AI's Ash are building early evidence for AI therapy approaches, but reviewers note the field is consolidating around established, clinically validated platforms rather than splashy launches."],
        "sources": [("PDP Spectra", "https://pdpspectra.com/blog/ai-mental-health-tech-2026/"), ("SunlitHappiness", "https://sunlithapiness.com/blog/ai-mental-health-apps-2026/")],
    },
]
